In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("./data/trainTitanic.csv")
df.head(15)

PassengerId  Survived  Pclass  \
0             1         0       3   
1             2         1       1   
2             3         1       3   
3             4         1       1   
4             5         0       3   
5             6         0       3   
6             7         0       1   
7             8         0       3   
8             9         1       3   
9            10         1       2   
10           11         1       3   
11           12         1       1   
12           13         0       3   
13           14         0       3   
14           15         0       3   

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1   
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                              Heikkinen, Miss. Laina  female  26.0      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                            Allen, Mr. William Henry    male  35.0      0   
5                                    Moran, Mr. James    male   NaN      0   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
7                      Palsson, Master. Gosta Leonard    male   2.0      3   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
12                     Saundercock, Mr. William Henry    male  20.0      0   
13                        Andersson, Mr. Anders Johan    male  39.0      1   
14               Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   

    Parch            Ticket     Fare Cabin Embarked  
0       0         A/5 21171   7.2500   NaN        S  
1       0          PC 17599  71.2833   C85        C  
2       0  STON/O2. 3101282   7.9250   NaN        S  
3       0            113803  53.1000  C123        S  
4       0            373450   8.0500   NaN        S  
5       0            330877   8.4583   NaN        Q  
6       0             17463  51.8625   E46        S  
7       1            349909  21.0750   NaN        S  
8       2            347742  11.1333   NaN        S  
9       0            237736  30.0708   NaN        C  
10      1           PP 9549  16.7000    G6        S  
11      0            113783  26.5500  C103        S  
12      0         A/5. 2151   8.0500   NaN        S  
13      5            347082  31.2750   NaN        S  
14      0            350406   7.8542   NaN        S

In [3]:
filter_df = df.drop('Name', axis=1)
filter_df = filter_df.drop('Ticket', axis=1)
filter_df = filter_df.drop('Cabin', axis=1)

In [4]:
filter_df.head(20)

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
0             1         0       3    male  22.0      1      0   7.2500   
1             2         1       1  female  38.0      1      0  71.2833   
2             3         1       3  female  26.0      0      0   7.9250   
3             4         1       1  female  35.0      1      0  53.1000   
4             5         0       3    male  35.0      0      0   8.0500   
5             6         0       3    male   NaN      0      0   8.4583   
6             7         0       1    male  54.0      0      0  51.8625   
7             8         0       3    male   2.0      3      1  21.0750   
8             9         1       3  female  27.0      0      2  11.1333   
9            10         1       2  female  14.0      1      0  30.0708   
10           11         1       3  female   4.0      1      1  16.7000   
11           12         1       1  female  58.0      0      0  26.5500   
12           13         0       3    male  20.0      0      0   8.0500   
13           14         0       3    male  39.0      1      5  31.2750   
14           15         0       3  female  14.0      0      0   7.8542   
15           16         1       2  female  55.0      0      0  16.0000   
16           17         0       3    male   2.0      4      1  29.1250   
17           18         1       2    male   NaN      0      0  13.0000   
18           19         0       3  female  31.0      1      0  18.0000   
19           20         1       3  female   NaN      0      0   7.2250   

   Embarked  
0         S  
1         C  
2         S  
3         S  
4         S  
5         Q  
6         S  
7         S  
8         S  
9         C  
10        S  
11        S  
12        S  
13        S  
14        S  
15        S  
16        Q  
17        S  
18        S  
19        C

## Test Decision Tree Building

In [5]:
test_df = filter_df
test_df = test_df[test_df["Age"].notna()]
test_df

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
0              1         0       3    male  22.0      1      0   7.2500   
1              2         1       1  female  38.0      1      0  71.2833   
2              3         1       3  female  26.0      0      0   7.9250   
3              4         1       1  female  35.0      1      0  53.1000   
4              5         0       3    male  35.0      0      0   8.0500   
..           ...       ...     ...     ...   ...    ...    ...      ...   
885          886         0       3  female  39.0      0      5  29.1250   
886          887         0       2    male  27.0      0      0  13.0000   
887          888         1       1  female  19.0      0      0  30.0000   
889          890         1       1    male  26.0      0      0  30.0000   
890          891         0       3    male  32.0      0      0   7.7500   

    Embarked  
0          S  
1          C  
2          S  
3          S  
4          S  
..       ...  
885        Q  
886        S  
887        S  
889        C  
890        Q  

[714 rows x 9 columns]

In [6]:
test_df.columns.tolist()

['PassengerId',
 'Survived',
 'Pclass',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Fare',
 'Embarked']

In [7]:
# Rearrange columns to make survived the last column
cols = test_df.columns.tolist()
cols = cols[0:1] + cols[2:] + cols[1:2]
cols

['PassengerId',
 'Pclass',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Fare',
 'Embarked',
 'Survived']

In [8]:
test_df = test_df[cols]
test_df

PassengerId  Pclass     Sex   Age  SibSp  Parch     Fare Embarked  \
0              1       3    male  22.0      1      0   7.2500        S   
1              2       1  female  38.0      1      0  71.2833        C   
2              3       3  female  26.0      0      0   7.9250        S   
3              4       1  female  35.0      1      0  53.1000        S   
4              5       3    male  35.0      0      0   8.0500        S   
..           ...     ...     ...   ...    ...    ...      ...      ...   
885          886       3  female  39.0      0      5  29.1250        Q   
886          887       2    male  27.0      0      0  13.0000        S   
887          888       1  female  19.0      0      0  30.0000        S   
889          890       1    male  26.0      0      0  30.0000        C   
890          891       3    male  32.0      0      0   7.7500        Q   

     Survived  
0           0  
1           1  
2           1  
3           1  
4           0  
..        ...  
885         0  
886         0  
887         1  
889         1  
890         0  

[714 rows x 9 columns]

In [9]:
# Convert categorical features to one hot encoding
sex_mapping = {'male': 0, 'female': 1}
embarked_mapping = {'S': 0, 'C': 1}

test_df['Sex'] = test_df['Sex'].map(sex_mapping)
test_df['Embarked'] = test_df['Embarked'].map(embarked_mapping)
test_df

PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked  Survived
0              1       3    0  22.0      1      0   7.2500       0.0         0
1              2       1    1  38.0      1      0  71.2833       1.0         1
2              3       3    1  26.0      0      0   7.9250       0.0         1
3              4       1    1  35.0      1      0  53.1000       0.0         1
4              5       3    0  35.0      0      0   8.0500       0.0         0
..           ...     ...  ...   ...    ...    ...      ...       ...       ...
885          886       3    1  39.0      0      5  29.1250       NaN         0
886          887       2    0  27.0      0      0  13.0000       0.0         0
887          888       1    1  19.0      0      0  30.0000       0.0         1
889          890       1    0  26.0      0      0  30.0000       1.0         1
890          891       3    0  32.0      0      0   7.7500       NaN         0

[714 rows x 9 columns]

In [10]:
test_df = test_df.dropna()
test_df

PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked  Survived
0              1       3    0  22.0      1      0   7.2500       0.0         0
1              2       1    1  38.0      1      0  71.2833       1.0         1
2              3       3    1  26.0      0      0   7.9250       0.0         1
3              4       1    1  35.0      1      0  53.1000       0.0         1
4              5       3    0  35.0      0      0   8.0500       0.0         0
..           ...     ...  ...   ...    ...    ...      ...       ...       ...
883          884       2    0  28.0      0      0  10.5000       0.0         0
884          885       3    0  25.0      0      0   7.0500       0.0         0
886          887       2    0  27.0      0      0  13.0000       0.0         0
887          888       1    1  19.0      0      0  30.0000       0.0         1
889          890       1    0  26.0      0      0  30.0000       1.0         1

[684 rows x 9 columns]

## Test with DecisionTree

In [11]:
from DecisionTree import *

In [12]:
test1 = DecisionTree(max_depth=5)
data_np = test_df.to_numpy(dtype=object)[:, 1:]

test1.build_tree(data=data_np)

In [13]:
test1.print_tree()

Feature 1 < 0.5
Left:
  Feature 2 < 9.5
  Left:
    Feature 3 < 2.5
    Left:
      Leaf: 1
    Right:
      Feature 2 < 3.5
      Left:
        Feature 2 < 2.5
        Left:
          Leaf: 0
        Right:
          Leaf: 1
      Right:
        Leaf: 0
  Right:
    Feature 0 < 1.5
    Left:
      Feature 2 < 53.0
      Left:
        Feature 5 < 25.9375
        Left:
          Leaf: 0
        Right:
          Leaf: 0
      Right:
        Feature 2 < 75.5
        Left:
          Leaf: 0
        Right:
          Leaf: 1
    Right:
      Feature 5 < 51.697900000000004
      Left:
        Feature 5 < 19.5
        Left:
          Leaf: 0
        Right:
          Leaf: 0
      Right:
        Feature 0 < 2.5
        Left:
          Leaf: 0
        Right:
          Leaf: 1
Right:
  Feature 0 < 2.5
  Left:
    Feature 2 < 2.5
    Left:
      Feature 0 < 1.5
      Left:
        Leaf: 0
      Right:
        Leaf: 1
    Right:
      Feature 5 < 28.85625
      Left:
        Feature 5 < 28.23125
  

In [14]:
test_pred = data_np[1:2,:]
test_pred

array([[1, 1, 38.0, 1, 0, 71.2833, 1.0, 1]], dtype=object)

In [15]:
test_pred.shape[0]

1

In [16]:
test_pred[0][3]

1

In [17]:
test1.predict_sample(test_pred)

1

In [18]:
test_preds = data_np[1:5,:]
test_preds

array([[1, 1, 38.0, 1, 0, 71.2833, 1.0, 1],
       [3, 1, 26.0, 0, 0, 7.925, 0.0, 1],
       [1, 1, 35.0, 1, 0, 53.1, 0.0, 1],
       [3, 0, 35.0, 0, 0, 8.05, 0.0, 0]], dtype=object)

In [23]:
test_preds

array([[1, 1, 38.0, 1, 0, 71.2833, 1.0, 1],
       [3, 1, 26.0, 0, 0, 7.925, 0.0, 1],
       [1, 1, 35.0, 1, 0, 53.1, 0.0, 1],
       [3, 0, 35.0, 0, 0, 8.05, 0.0, 0]], dtype=object)

In [24]:
test_preds.shape

(4, 8)

In [27]:
test_preds[:, test_preds.shape[1]-1:]

array([[1],
       [1],
       [1],
       [0]], dtype=object)

In [28]:
test_preds[:, :test_preds.shape[1]-1]

array([[1, 1, 38.0, 1, 0, 71.2833, 1.0],
       [3, 1, 26.0, 0, 0, 7.925, 0.0],
       [1, 1, 35.0, 1, 0, 53.1, 0.0],
       [3, 0, 35.0, 0, 0, 8.05, 0.0]], dtype=object)

In [19]:
results = test1.predict(test_preds)
results

array([[1],
       [0],
       [1],
       [0]])

In [20]:
# test_np = test_df.to_numpy(dtype=object)[0:]
# test_np = test_np[:, 1:] # Remove id
# test_np_labels = test_df.columns.values
# test_np

In [21]:
# def calculate_gini(data):
#     true_val = data[data[:, test_np.shape[1]-1] == 1]
#     false_val = data[data[:, test_np.shape[1]-1] == 0]

#     return 1 - (len(true_val)/len(data))**2 - (len(false_val)/len(data))**2

In [22]:
# lowest_gini = float("inf")
# lowest_gini_feature = -1
# lowest_gini_threshold = -1

# for i in range(0, test_np.shape[1] - 1):
#     print(i)
#     print(np.unique(test_np[:, i]))

#     unique_values = np.unique(test_np[:, i])

#     # Calculate gini impurity
#     for j in range(unique_values.shape[0]-1):
#         filter_value = (unique_values[j]+unique_values[j+1])/2
#         print(filter_value)
    
#         left = test_np[test_np[:, i] >= filter_value]
#         right = test_np[test_np[:, i] < filter_value]
#         print(left)
#         print(right)
#         assert len(left) + len(right) == len(test_np)

#         total_gini_impurity = (len(left)/len(test_np))*calculate_gini(left) + (len(right)/len(test_np))*calculate_gini(right)
#         print(total_gini_impurity)

#         if total_gini_impurity < lowest_gini:
#             lowest_gini = total_gini_impurity
#             lowest_gini_feature = i
#             lowest_gini_threshold = filter_value


#     print()
#     print()