In [3]:
import pandas as pd
import numpy as np
import os

In [4]:
os.chdir("..")

In [ ]:
df = pd.read_csv("./data/test/trainTitanic.csv")
df.head(15)

PassengerId  Survived  Pclass  \
0             1         0       3   
1             2         1       1   
2             3         1       3   
3             4         1       1   
4             5         0       3   
5             6         0       3   
6             7         0       1   
7             8         0       3   
8             9         1       3   
9            10         1       2   
10           11         1       3   
11           12         1       1   
12           13         0       3   
13           14         0       3   
14           15         0       3   

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1   
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                              Heikkinen, Miss. Laina  female  26.0      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                            Allen, Mr. William Henry    male  35.0      0   
5                                    Moran, Mr. James    male   NaN      0   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
7                      Palsson, Master. Gosta Leonard    male   2.0      3   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
12                     Saundercock, Mr. William Henry    male  20.0      0   
13                        Andersson, Mr. Anders Johan    male  39.0      1   
14               Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   

    Parch            Ticket     Fare Cabin Embarked  
0       0         A/5 21171   7.2500   NaN        S  
1       0          PC 17599  71.2833   C85        C  
2       0  STON/O2. 3101282   7.9250   NaN        S  
3       0            113803  53.1000  C123        S  
4       0            373450   8.0500   NaN        S  
5       0            330877   8.4583   NaN        Q  
6       0             17463  51.8625   E46        S  
7       1            349909  21.0750   NaN        S  
8       2            347742  11.1333   NaN        S  
9       0            237736  30.0708   NaN        C  
10      1           PP 9549  16.7000    G6        S  
11      0            113783  26.5500  C103        S  
12      0         A/5. 2151   8.0500   NaN        S  
13      5            347082  31.2750   NaN        S  
14      0            350406   7.8542   NaN        S

In [4]:
filter_df = df.drop('Name', axis=1)
filter_df = filter_df.drop('Ticket', axis=1)
filter_df = filter_df.drop('Cabin', axis=1)

In [5]:
filter_df.head(20)

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
0             1         0       3    male  22.0      1      0   7.2500   
1             2         1       1  female  38.0      1      0  71.2833   
2             3         1       3  female  26.0      0      0   7.9250   
3             4         1       1  female  35.0      1      0  53.1000   
4             5         0       3    male  35.0      0      0   8.0500   
5             6         0       3    male   NaN      0      0   8.4583   
6             7         0       1    male  54.0      0      0  51.8625   
7             8         0       3    male   2.0      3      1  21.0750   
8             9         1       3  female  27.0      0      2  11.1333   
9            10         1       2  female  14.0      1      0  30.0708   
10           11         1       3  female   4.0      1      1  16.7000   
11           12         1       1  female  58.0      0      0  26.5500   
12           13         0       3    male  20.0      0      0   8.0500   
13           14         0       3    male  39.0      1      5  31.2750   
14           15         0       3  female  14.0      0      0   7.8542   
15           16         1       2  female  55.0      0      0  16.0000   
16           17         0       3    male   2.0      4      1  29.1250   
17           18         1       2    male   NaN      0      0  13.0000   
18           19         0       3  female  31.0      1      0  18.0000   
19           20         1       3  female   NaN      0      0   7.2250   

   Embarked  
0         S  
1         C  
2         S  
3         S  
4         S  
5         Q  
6         S  
7         S  
8         S  
9         C  
10        S  
11        S  
12        S  
13        S  
14        S  
15        S  
16        Q  
17        S  
18        S  
19        C

## Test Decision Tree Building

In [6]:
test_df = filter_df
test_df = test_df[test_df["Age"].notna()]
test_df

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
0              1         0       3    male  22.0      1      0   7.2500   
1              2         1       1  female  38.0      1      0  71.2833   
2              3         1       3  female  26.0      0      0   7.9250   
3              4         1       1  female  35.0      1      0  53.1000   
4              5         0       3    male  35.0      0      0   8.0500   
..           ...       ...     ...     ...   ...    ...    ...      ...   
885          886         0       3  female  39.0      0      5  29.1250   
886          887         0       2    male  27.0      0      0  13.0000   
887          888         1       1  female  19.0      0      0  30.0000   
889          890         1       1    male  26.0      0      0  30.0000   
890          891         0       3    male  32.0      0      0   7.7500   

    Embarked  
0          S  
1          C  
2          S  
3          S  
4          S  
..       ...  
885        Q  
886        S  
887        S  
889        C  
890        Q  

[714 rows x 9 columns]

In [7]:
test_df.columns.tolist()

['PassengerId',
 'Survived',
 'Pclass',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Fare',
 'Embarked']

In [8]:
# Rearrange columns to make survived the last column
cols = test_df.columns.tolist()
cols = cols[0:1] + cols[2:] + cols[1:2]
cols

['PassengerId',
 'Pclass',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Fare',
 'Embarked',
 'Survived']

In [9]:
test_df = test_df[cols]
test_df

PassengerId  Pclass     Sex   Age  SibSp  Parch     Fare Embarked  \
0              1       3    male  22.0      1      0   7.2500        S   
1              2       1  female  38.0      1      0  71.2833        C   
2              3       3  female  26.0      0      0   7.9250        S   
3              4       1  female  35.0      1      0  53.1000        S   
4              5       3    male  35.0      0      0   8.0500        S   
..           ...     ...     ...   ...    ...    ...      ...      ...   
885          886       3  female  39.0      0      5  29.1250        Q   
886          887       2    male  27.0      0      0  13.0000        S   
887          888       1  female  19.0      0      0  30.0000        S   
889          890       1    male  26.0      0      0  30.0000        C   
890          891       3    male  32.0      0      0   7.7500        Q   

     Survived  
0           0  
1           1  
2           1  
3           1  
4           0  
..        ...  
885         0  
886         0  
887         1  
889         1  
890         0  

[714 rows x 9 columns]

In [10]:
# Convert categorical features to one hot encoding
sex_mapping = {'male': 0, 'female': 1}
embarked_mapping = {'S': 0, 'C': 1}

test_df['Sex'] = test_df['Sex'].map(sex_mapping)
test_df['Embarked'] = test_df['Embarked'].map(embarked_mapping)
test_df

PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked  Survived
0              1       3    0  22.0      1      0   7.2500       0.0         0
1              2       1    1  38.0      1      0  71.2833       1.0         1
2              3       3    1  26.0      0      0   7.9250       0.0         1
3              4       1    1  35.0      1      0  53.1000       0.0         1
4              5       3    0  35.0      0      0   8.0500       0.0         0
..           ...     ...  ...   ...    ...    ...      ...       ...       ...
885          886       3    1  39.0      0      5  29.1250       NaN         0
886          887       2    0  27.0      0      0  13.0000       0.0         0
887          888       1    1  19.0      0      0  30.0000       0.0         1
889          890       1    0  26.0      0      0  30.0000       1.0         1
890          891       3    0  32.0      0      0   7.7500       NaN         0

[714 rows x 9 columns]

In [11]:
test_df = test_df.dropna()
test_df

PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked  Survived
0              1       3    0  22.0      1      0   7.2500       0.0         0
1              2       1    1  38.0      1      0  71.2833       1.0         1
2              3       3    1  26.0      0      0   7.9250       0.0         1
3              4       1    1  35.0      1      0  53.1000       0.0         1
4              5       3    0  35.0      0      0   8.0500       0.0         0
..           ...     ...  ...   ...    ...    ...      ...       ...       ...
883          884       2    0  28.0      0      0  10.5000       0.0         0
884          885       3    0  25.0      0      0   7.0500       0.0         0
886          887       2    0  27.0      0      0  13.0000       0.0         0
887          888       1    1  19.0      0      0  30.0000       0.0         1
889          890       1    0  26.0      0      0  30.0000       1.0         1

[684 rows x 9 columns]

## Test with DecisionTree

In [12]:
from DecisionTree import DecisionTree

In [13]:
test1 = DecisionTree.DecisionTree(max_depth=5)
data_np = test_df.to_numpy(dtype=object)[:, 1:]

test1.build_tree(data=data_np)

In [14]:
data_np.shape[0]

684

In [15]:
test1.print_tree()

Feature 1 < 0.5
Left:
  Feature 2 < 9.5
  Left:
    Feature 3 < 2.5
    Left:
      Leaf: 1
    Right:
      Feature 2 < 3.5
      Left:
        Feature 2 < 2.5
        Left:
          Leaf: 0
        Right:
          Leaf: 1
      Right:
        Leaf: 0
  Right:
    Feature 0 < 1.5
    Left:
      Feature 2 < 53.0
      Left:
        Feature 5 < 25.9375
        Left:
          Leaf: 0
        Right:
          Leaf: 0
      Right:
        Feature 2 < 75.5
        Left:
          Leaf: 0
        Right:
          Leaf: 1
    Right:
      Feature 5 < 51.697900000000004
      Left:
        Feature 5 < 19.5
        Left:
          Leaf: 0
        Right:
          Leaf: 0
      Right:
        Feature 0 < 2.5
        Left:
          Leaf: 0
        Right:
          Leaf: 1
Right:
  Feature 0 < 2.5
  Left:
    Feature 2 < 2.5
    Left:
      Feature 0 < 1.5
      Left:
        Leaf: 0
      Right:
        Leaf: 1
    Right:
      Feature 5 < 28.85625
      Left:
        Feature 5 < 28.23125
  

In [16]:
test_pred = data_np[1:2,:]
test_pred

array([[1, 1, 38.0, 1, 0, 71.2833, 1.0, 1]], dtype=object)

In [17]:
test_pred.shape[0]

1

In [18]:
test_pred[0][3]

1

In [19]:
test1.predict_sample(test_pred)

1

In [20]:
test_preds = data_np[1:5,:]
test_preds

array([[1, 1, 38.0, 1, 0, 71.2833, 1.0, 1],
       [3, 1, 26.0, 0, 0, 7.925, 0.0, 1],
       [1, 1, 35.0, 1, 0, 53.1, 0.0, 1],
       [3, 0, 35.0, 0, 0, 8.05, 0.0, 0]], dtype=object)

In [21]:
test_preds

array([[1, 1, 38.0, 1, 0, 71.2833, 1.0, 1],
       [3, 1, 26.0, 0, 0, 7.925, 0.0, 1],
       [1, 1, 35.0, 1, 0, 53.1, 0.0, 1],
       [3, 0, 35.0, 0, 0, 8.05, 0.0, 0]], dtype=object)

In [22]:
test_preds.shape

(4, 8)

In [23]:
test_preds[:, test_preds.shape[1]-1:]

array([[1],
       [1],
       [1],
       [0]], dtype=object)

In [24]:
test_preds[:, :test_preds.shape[1]-1]

array([[1, 1, 38.0, 1, 0, 71.2833, 1.0],
       [3, 1, 26.0, 0, 0, 7.925, 0.0],
       [1, 1, 35.0, 1, 0, 53.1, 0.0],
       [3, 0, 35.0, 0, 0, 8.05, 0.0]], dtype=object)

In [25]:
results = test1.predict(test_preds)
results

array([[1],
       [0],
       [1],
       [0]])

In [26]:
data_np

array([[3, 0, 22.0, ..., 7.25, 0.0, 0],
       [1, 1, 38.0, ..., 71.2833, 1.0, 1],
       [3, 1, 26.0, ..., 7.925, 0.0, 1],
       ...,
       [2, 0, 27.0, ..., 13.0, 0.0, 0],
       [1, 1, 19.0, ..., 30.0, 0.0, 1],
       [1, 0, 26.0, ..., 30.0, 1.0, 1]], dtype=object)

In [27]:
test_array = np.array([[]], dtype=object)
test_array

array([], shape=(1, 0), dtype=object)

In [28]:
test_array = np.empty(data_np.shape, dtype=object)
test_array

array([[None, None, None, ..., None, None, None],
       [None, None, None, ..., None, None, None],
       [None, None, None, ..., None, None, None],
       ...,
       [None, None, None, ..., None, None, None],
       [None, None, None, ..., None, None, None],
       [None, None, None, ..., None, None, None]], dtype=object)

In [29]:
for i in range(test_array.shape[0]):
    random_row = data_np[np.random.randint(data_np.shape[0])]
    test_array[i] = random_row

In [30]:
test_array

array([[2, 1, 34.0, ..., 23.0, 0.0, 1],
       [1, 1, 39.0, ..., 79.65, 0.0, 1],
       [2, 0, 19.0, ..., 36.75, 0.0, 0],
       ...,
       [1, 1, 60.0, ..., 75.25, 1.0, 1],
       [2, 1, 25.0, ..., 26.0, 0.0, 1],
       [1, 1, 58.0, ..., 153.4625, 0.0, 1]], dtype=object)

In [31]:
test_array

array([[2, 1, 34.0, ..., 23.0, 0.0, 1],
       [1, 1, 39.0, ..., 79.65, 0.0, 1],
       [2, 0, 19.0, ..., 36.75, 0.0, 0],
       ...,
       [1, 1, 60.0, ..., 75.25, 1.0, 1],
       [2, 1, 25.0, ..., 26.0, 0.0, 1],
       [1, 1, 58.0, ..., 153.4625, 0.0, 1]], dtype=object)

In [32]:
tree_bagger = DecisionTree.DecisionTree()

In [33]:
bagged_np = tree_bagger.perform_bagging(data_np)
bagged_np

array([[2, 1, 5.0, ..., 27.75, 0.0, 1],
       [3, 0, 4.0, ..., 27.9, 0.0, 0],
       [3, 0, 19.0, ..., 7.8958, 0.0, 0],
       ...,
       [3, 0, 24.5, ..., 8.05, 0.0, 0],
       [1, 0, 0.92, ..., 151.55, 0.0, 1],
       [3, 0, 38.0, ..., 7.8958, 0.0, 0]], dtype=object)

In [34]:
data_np_float = np.array(data_np, dtype=np.float64)
bagged_np_float = np.array(bagged_np, dtype=np.float64)

In [35]:
data_np_float.shape

(684, 8)

In [36]:
np.unique(data_np_float, axis=0).shape

(646, 8)

In [37]:
bagged_np_float.shape

(684, 8)

In [38]:
np.unique(bagged_np_float, axis=0).shape

(405, 8)

In [39]:
for i in range(0, 9):
    print(i)

0
1
2
3
4
5
6
7
8


In [40]:
data_np.shape

(684, 8)

In [41]:
data_np

array([[3, 0, 22.0, ..., 7.25, 0.0, 0],
       [1, 1, 38.0, ..., 71.2833, 1.0, 1],
       [3, 1, 26.0, ..., 7.925, 0.0, 1],
       ...,
       [2, 0, 27.0, ..., 13.0, 0.0, 0],
       [1, 1, 19.0, ..., 30.0, 0.0, 1],
       [1, 0, 26.0, ..., 30.0, 1.0, 1]], dtype=object)

In [42]:
# Randomly selecting features (application in Random Forest)
data_n = data_np.copy()
n_features = 3

if n_features < data_n.shape[1] - 1:
    data_n_labels = data_n[:,(data_n.shape[1]-1):data_n.shape[1]]
    data_n_data = data_n[:,:data_n.shape[1]-1]

    shuffled_indices = np.random.permutation(data_n_data.shape[1])
    data_n_data = data_n_data[:, shuffled_indices]
    data_n_data = data_n_data[:, :n_features]

    data_n = np.append(data_n_data, data_n_labels, axis=1)

data_n

array([[0.0, 22.0, 1, 0],
       [1.0, 38.0, 1, 1],
       [0.0, 26.0, 0, 1],
       ...,
       [0.0, 27.0, 0, 0],
       [0.0, 19.0, 0, 1],
       [1.0, 26.0, 0, 1]], dtype=object)

In [43]:
data_np.shape

(684, 8)

In [44]:
data_np[:, :3]

array([[3, 0, 22.0],
       [1, 1, 38.0],
       [3, 1, 26.0],
       ...,
       [2, 0, 27.0],
       [1, 1, 19.0],
       [1, 0, 26.0]], dtype=object)

In [45]:
np.append(data_np, data_np[:,7:8], axis=1)

array([[3, 0, 22.0, ..., 0.0, 0, 0],
       [1, 1, 38.0, ..., 1.0, 1, 1],
       [3, 1, 26.0, ..., 0.0, 1, 1],
       ...,
       [2, 0, 27.0, ..., 0.0, 0, 0],
       [1, 1, 19.0, ..., 0.0, 1, 1],
       [1, 0, 26.0, ..., 1.0, 1, 1]], dtype=object)

In [46]:
data_np[:,7:8]+data_np

array([[3, 0, 22.0, ..., 7.25, 0.0, 0],
       [2, 2, 39.0, ..., 72.2833, 2.0, 2],
       [4, 2, 27.0, ..., 8.925, 1.0, 2],
       ...,
       [2, 0, 27.0, ..., 13.0, 0.0, 0],
       [2, 2, 20.0, ..., 31.0, 1.0, 2],
       [2, 1, 27.0, ..., 31.0, 2.0, 2]], dtype=object)

In [47]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Shuffle columns
shuffled_indices = np.random.permutation(arr.shape[1])  # Generate random column indices
shuffled_arr = arr[:, shuffled_indices]  # Reorder columns

print("Original Array:\n", arr)
print("Shuffled Array:\n", shuffled_arr)

Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shuffled Array:
 [[ 2  3  1  4]
 [ 6  7  5  8]
 [10 11  9 12]]


In [48]:
set1Test = set(range(10))
set1Test

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [49]:
import random
random_element = random.choice(tuple(set1Test))
set1Test.remove(random_element)

In [50]:
set1Test

{0, 1, 2, 3, 4, 5, 6, 7, 8}

In [51]:
# test_np = test_df.to_numpy(dtype=object)[0:]
# test_np = test_np[:, 1:] # Remove id
# test_np_labels = test_df.columns.values
# test_np

In [52]:
# def calculate_gini(data):
#     true_val = data[data[:, test_np.shape[1]-1] == 1]
#     false_val = data[data[:, test_np.shape[1]-1] == 0]

#     return 1 - (len(true_val)/len(data))**2 - (len(false_val)/len(data))**2

In [53]:
# lowest_gini = float("inf")
# lowest_gini_feature = -1
# lowest_gini_threshold = -1

# for i in range(0, test_np.shape[1] - 1):
#     print(i)
#     print(np.unique(test_np[:, i]))

#     unique_values = np.unique(test_np[:, i])

#     # Calculate gini impurity
#     for j in range(unique_values.shape[0]-1):
#         filter_value = (unique_values[j]+unique_values[j+1])/2
#         print(filter_value)
    
#         left = test_np[test_np[:, i] >= filter_value]
#         right = test_np[test_np[:, i] < filter_value]
#         print(left)
#         print(right)
#         assert len(left) + len(right) == len(test_np)

#         total_gini_impurity = (len(left)/len(test_np))*calculate_gini(left) + (len(right)/len(test_np))*calculate_gini(right)
#         print(total_gini_impurity)

#         if total_gini_impurity < lowest_gini:
#             lowest_gini = total_gini_impurity
#             lowest_gini_feature = i
#             lowest_gini_threshold = filter_value


#     print()
#     print()

In [5]:
import pandas as pd

In [10]:
df = pd.read_csv("./data/final_dataset.csv")

In [11]:
df

PLAYER_1  PLAYER_2  ATP_POINT_DIFF  ATP_RANK_DIFF   AGE_DIFF  \
0      101746.0  101142.0         -1028.0           69.0  -5.000000   
1      100587.0  101613.0          -257.0          126.0  10.300000   
2      101179.0  101601.0           352.0         -135.0   3.700000   
3      101117.0  101332.0            19.0           -7.0   2.000000   
4      101901.0  101735.0          -734.0          162.0  -0.900000   
...         ...       ...             ...            ...        ...   
95486  207989.0  104925.0          3110.0           -4.0 -15.953457   
95487  132283.0  210097.0         -1254.0           35.0   7.413415   
95488  200282.0  206173.0         -8295.0            7.0   2.493498   
95489  206173.0  210097.0          9550.0          -19.0   1.147844   
95490  100644.0  206173.0         -4195.0            1.0   4.323066   

       HEIGHT_DIFF  BEST_OF  DRAW_SIZE  H2H_DIFF  H2H_SURFACE_DIFF  \
0             -5.0        3         32      -0.0              -0.0   
1              8.0        3         32      -0.0              -0.0   
2              0.0        3         32       0.0               0.0   
3              7.0        3         32       0.0               0.0   
4            -11.0        3         32       0.0               0.0   
...            ...      ...        ...       ...               ...   
95486         -5.0        5        128      -1.0              -2.0   
95487         -2.0        5        128      -0.0              -1.0   
95488         -8.0        5        128      -9.0              -8.0   
95489         -2.0        5        128       3.0               2.0   
95490          7.0        5        128       2.0               2.0   

       DIFF_N_GAMES  WIN_LAST_3_DIFF  WIN_LAST_5_DIFF  WIN_LAST_10_DIFF  \
0              -0.0             -0.0             -0.0              -0.0   
1              -0.0             -0.0             -0.0              -0.0   
2               0.0              0.0              0.0               0.0   
3               0.0              0.0              0.0               0.0   
4               0.0              0.0              0.0               0.0   
...             ...              ...              ...               ...   
95486       -1033.0             -0.0             -0.0              -0.1   
95487         171.0             -0.0              0.2              -0.2   
95488          56.0             -0.0             -0.2              -0.5   
95489         218.0              0.0              0.2               0.2   
95490         304.0             -0.0             -0.0              -0.1   

       WIN_LAST_25_DIFF  WIN_LAST_50_DIFF  WIN_LAST_100_DIFF  \
0                 -0.00             -0.00              -0.00   
1                 -0.00             -0.00              -0.00   
2                  0.00              0.00               0.00   
3                  0.00              0.00               0.00   
4                  0.00              0.00               0.00   
...                 ...               ...                ...   
95486             -0.12              0.04              -0.05   
95487             -0.16             -0.14              -0.13   
95488             -0.32             -0.26              -0.22   
95489              0.24              0.32               0.30   
95490             -0.16             -0.14              -0.15   

       P_ACE_LAST_3_DIFF  P_DF_LAST_3_DIFF  P_1ST_IN_LAST_3_DIFF  \
0              -0.000000         -0.000000             -0.000000   
1              -0.000000         -0.000000             -0.000000   
2               0.000000          0.000000              0.000000   
3               0.000000          0.000000              0.000000   
4               0.000000          0.000000              0.000000   
...                  ...               ...                   ...   
95486           5.606295         -1.662195             -6.493292   
95487           3.408474         -1.288858             -5.069536   
95488          -1.931250       

In [13]:
pd.set_option('display.max_columns', None)
df[((df["PLAYER_1"] == 207989) & (df["PLAYER_2"] == 104925)) | ((df["PLAYER_2"] == 207989) & (df["PLAYER_1"] == 104925))]

PLAYER_1  PLAYER_2  ATP_POINT_DIFF  ATP_RANK_DIFF   AGE_DIFF  \
87971  104925.0  207989.0          4582.0           -8.0  16.000000   
91031  207989.0  104925.0           860.0           -2.0 -16.000000   
91328  207989.0  104925.0            80.0           -1.0 -16.000000   
91645  207989.0  104925.0           600.0           -1.0 -16.000000   
92333  104925.0  207989.0          1490.0           -1.0  15.900000   
94137  104925.0  207989.0           230.0           -1.0  16.000000   
94433  207989.0  104925.0          -330.0            1.0 -15.900000   
95486  207989.0  104925.0          3110.0           -4.0 -15.953457   

       HEIGHT_DIFF  BEST_OF  DRAW_SIZE  H2H_DIFF  H2H_SURFACE_DIFF  \
87971          5.0        3         64      -0.0              -0.0   
91031         -5.0        5        128       1.0               1.0   
91328         -5.0        5        128       0.0               0.0   
91645         -5.0        3         64       1.0              -0.0   
92333          5.0        3          8       0.0               1.0   
94137          5.0        5        128       1.0              -1.0   
94433         -5.0        3         64      -0.0              -0.0   
95486         -5.0        5        128      -1.0              -2.0   

       DIFF_N_GAMES  WIN_LAST_3_DIFF  WIN_LAST_5_DIFF  WIN_LAST_10_DIFF  \
87971        1072.0        -0.000000             -0.4              -0.2   
91031       -1060.0        -0.000000             -0.0              -0.0   
91328       -1056.0         0.000000              0.0               0.0   
91645       -1053.0        -0.000000             -0.0              -0.0   
92333        1052.0         0.333333              0.4               0.4   
94137        1046.0        -0.000000             -0.0               0.1   
94433       -1045.0        -0.000000              0.2               0.1   
95486       -1033.0        -0.000000             -0.0              -0.1   

       WIN_LAST_25_DIFF  WIN_LAST_50_DIFF  WIN_LAST_100_DIFF  \
87971             -0.00              0.06           0.142727   
91031              0.08             -0.02          -0.030000   
91328              0.08              0.02          -0.040000   
91645              0.04              0.02          -0.030000   
92333              0.20              0.06           0.060000   
94137             -0.08              0.06           0.040000   
94433              0.12             -0.00          -0.020000   
95486             -0.12              0.04          -0.050000   

       P_ACE_LAST_3_DIFF  P_DF_LAST_3_DIFF  P_1ST_IN_LAST_3_DIFF  \
87971           0.948078          0.994104             -2.881098   
91031          -1.139440         -2.285771              6.185805   
91328          -5.140897          2.784855              1.511243   
91645           0.041420          2.386249             -0.237625   
92333          10.999507          1.366845             -3.427161   
94137           2.442315          0.381111              3.804921   
94433           0.537759          2.181601             -2.133458   
95486           5.606295         -1.662195             -6.493292   

       P_1ST_WON_LAST_3_DIFF  P_2ND_WON_LAST_3_DIFF  P_BP_SAVED_LAST_3_DIFF  \
87971             -10.771559             -10.626632                3.174603   
91031              -1.367738              15.177734                1.309524   
91328              -2.510139               0.374270               -6.944444   
91645               0.439822              -1.353792              -27.061404   
92333              13.281530               5.258981               21.428571   
94137              10.942316               3.254491               26.153846   
94433               5.091205             -17.459861                4.444444   
95486               4.925324               4.204545              -20.000000   

       P_ACE_LAST_5_DIFF  P_DF_LAST_5_DIFF  P_1ST_IN_LAST_5_DIFF  \
87971           1.594690          1.581781             -3.153694   
91031          -2.2809